# Math 428 - Homework for 03/27/19

In [2]:
import numpy as np
# The matrix itself
matr = np.array([[1, 4, 9, 16, 25],
                 [4, 9, 16, 25, 36],
                 [9, 16, 25, 36, 49],
                 [16, 25, 36, 49, 64],
                 [25, 36, 49, 64, 81]])

# The inverse of the matrix
matr_inv = np.linalg.inv(matr)

### The Matrix $A$, and its inverse $A^{-1}$

In [43]:
print ("A:\n", np.c_[matr], "\n\nA-Inverse:\n", np.c_[matr_inv])

A:
 [[ 1  4  9 16 25]
 [ 4  9 16 25 36]
 [ 9 16 25 36 49]
 [16 25 36 49 64]
 [25 36 49 64 81]] 

A-Inverse:
 [[-2.79988551e+14  6.57270421e+14 -2.91879957e+14 -2.68097145e+14
   1.82695232e+14]
 [ 5.21059774e+14 -1.32751328e+15  8.56181206e+14  1.85938343e+14
  -2.35666039e+14]
 [ 1.16751983e+14  3.89173276e+13 -8.17263879e+14  1.05076784e+15
  -3.89173276e+14]
 [-6.76729085e+14  1.27562351e+15  2.33503965e+14 -1.58696213e+15
   7.54563740e+14]
 [ 3.18905879e+14 -6.44297978e+14  1.94586638e+13  6.18353093e+14
  -3.12419657e+14]]


### The row sums of $A$ and $A^{-1}$

In [55]:
# Calculate the row sums of the matrix and its inverse
matr_row_sums = np.sum(np.absolute(matr), axis=1)
matr_inv_row_sums = np.sum(np.absolute(matr_inv), axis=1)

print ("Row sum of A:\n", np.c_[matr_row_sums],
       "\n\nRow Sum of A-Inverse:\n", np.c_[matr_inv_row_sums])

# Compute the condition number
cond_number = np.amax(matr_row_sums) * np.amax(matr_inv_row_sums)
print ("\nThe condition number of the matrix is: %i" % cond_number)

Row sum of A:
 [[ 55]
 [ 90]
 [135]
 [190]
 [255]] 

Row Sum of A-Inverse:
 [[1.67993131e+15]
 [3.12635864e+15]
 [2.41287431e+15]
 [4.52738243e+15]
 [1.91343527e+15]]

The condition number of the matrix is: 1154482519649999872


In [37]:
c = np.log10(cond_number)
t = abs(np.log10(2 ** -24))
print ("Suspected Digits in A: %i, Significant Digits in IEEE standards: %i" % (c ,t))

Suspected Digits of A: 18, Significant Digits in IEEE standards: 7


Since the number of suspected digits is so much higher than the number of significant digits in the IEEE standard, the solution is only valid to $t-c$ digits, which is -11 (zero). Meaning the solution may be entirely invalid, because __the system is so ill-conditioned__.
## Part (b)
### Normalizing the matrix into $A_N$ and $A_N^{-1}$

In [56]:
# Normalize the matrix
matr_norm = [matr[i] / np.amax(matr[i]) for i in range(len(matr))]
# Calcualate the inverse of the normalized matrix
matr_norm_inv = np.linalg.inv(matr_norm)
print ("Normalized A:\n", np.c_[matr_norm],
       "\n\nInverse of Normalized A:\n", np.c_[matr_norm_inv])

Normalized A:
 [[0.04       0.16       0.36       0.64       1.        ]
 [0.11111111 0.25       0.44444444 0.69444444 1.        ]
 [0.18367347 0.32653061 0.51020408 0.73469388 1.        ]
 [0.25       0.390625   0.5625     0.765625   1.        ]
 [0.30864198 0.44444444 0.60493827 0.79012346 1.        ]] 

Inverse of Normalized A:
 [[ 1.79512102e+14 -1.25227643e+15  3.00239975e+15 -3.00239975e+15
   1.07276432e+15]
 [ 3.59024205e+13  1.55098457e+15 -6.75539944e+15  9.00719925e+15
  -3.83868680e+15]
 [-1.18477988e+15  2.86070487e+15  2.25179981e+15 -9.00719925e+15
   5.07947445e+15]
 [ 1.54380408e+15 -5.36525772e+15  3.75299969e+15  3.00239975e+15
  -2.93394580e+15]
 [-5.74438728e+14  2.20584472e+15 -2.25179981e+15 -0.00000000e+00
   6.20393826e+14]]


### Row sums of the normalized matrix $A_N$ and $A_N^{-1}$

In [57]:
# Calculate the row sums, now using the normalized matrices
matr_norm_row_sums = np.sum(np.absolute(matr_norm), axis=1)
matr_norm_inv_row_sums = np.sum(np.absolute(matr_norm_inv), axis=1)

print ("Row sum of A:\n", np.c_[matr_norm_row_sums],
       "\n\nRow Sum of A-Inverse:\n", np.c_[matr_norm_inv_row_sums])

# Compute the condition number
norm_cond_number = np.amax(matr_norm_row_sums) * np.amax(matr_norm_inv_row_sums)
print ("\nThe condition number of the normalized matrix is: %i" % norm_cond_number)

Row sum of A:
 [[2.2       ]
 [2.5       ]
 [2.75510204]
 [2.96875   ]
 [3.14814815]] 

Row Sum of A-Inverse:
 [[8.50935236e+15]
 [2.11881725e+16]
 [2.03839583e+16]
 [1.65984070e+16]
 [5.65247708e+15]]

The condition number of the normalized matrix is: 66703505960518768


In [58]:
c_norm = np.log10(norm_cond_number)
t_norm = abs(np.log10(2 ** -24))
print ("Suspected Digits in A: %i, Significant Digits in IEEE standards: %i" % (c_norm , t_norm))

Suspected Digits in A: 16, Significant Digits in IEEE standards: 7


Once again, due to the terrible conditioning of the system, the digits of precision lost (computed by $t-c$), is a negative number (0); meaning all the digits may be invalid.